# Setup
title:        Entity Type Walkthrough
tagline:      Step-by-step instructions to create a custom entity type in Drupal 8
baseurl:      "/event"

# About/contact
author:
  name:       The Drupal Entity Training Team
  url:        https://github.com/drupal-entity-training

markdown: kramdown
highlighter: rouge
