# Setup
title:        Guide to creating a custom entity type in Drupal 8
tagline:      A step-by-step walkthrough of creating a Drupal 8 module with a custom <em>Event</em> entity type
baseurl:      "/event"

# About/contact
author:
  name:       The Drupal Entity Training Team
  url:        https://github.com/drupal-entity-training

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
